sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull debian:buster

script:
- docker build -t novsyama/debian-japanese:buster .
- docker images

deploy:
  provider: script
  script: bash push
  on:
    branch: buster

notifications:
  email: false
