sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull debian:stretch

script:
- docker build -t novsyama/debian-japanese:stretch .
- docker images

deploy:
  provider: script
  script: bash push
  on:
    branch: stretch

notifications:
  email: false
