sudo: required

language: ruby

services:
  - docker

env:
  - RELEASE=jessie

script:
- bash build

deploy:
  provider: script
  script: bash push
  on:
    branch: jessie

notifications:
  email: false
