sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull debian:jessie

script:
- docker build -t novsyama/debian-japanese:jessie .
- docker images

deploy:
  provider: script
  script: bash push
  on:
    branch: master

notifications:
  email: false
