sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull debian:jessie

script:
- docker build -t novsyama/debian-japanese:jessie --build-arg VCS_REF=`git rev-parse --short HEAD` .
- docker images

deploy:
  provider: script
  script: bash push
  on:
    branch: jessie

notifications:
  email: false
