sudo: required

language: ruby

services:
  - docker

env:
  - RELEASE=bullseye

script:
- bash build

deploy:
  provider: script
  script: bash push
  on:
    branch: ${RELEASE}

notifications:
  email: false
