#!/bin/bash

TAG=`date +%Y%m%d`
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag novsyama/debian-japanese:${RELEASE} novsyama/debian-japanese:${RELEASE}-${TAG}
docker push novsyama/debian-japanese:${RELEASE}-${TAG}
docker push novsyama/debian-japanese:${RELEASE}
