#!/bin/bash

TAG=`date +%Y%m%d`
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag novsyama/debian-japanese novsyama/debian-japanese:${TAG}
docker push novsyama/debian-japanese:${TAG}
docker push novsyama/debian-japanese
